export const appConstants = {
    FETCH_ORDERS: 'FETCH_ORDERS',
    FETCH_EMPLOYMENT_TYPES: 'FETCH_EMPLOYMENT_TYPES',
    FETCH_PLANS: 'FETCH_PLANS',
    GET_REPAYMENT_BREAKDOWN: 'GET_REPAYMENT_BREAKDOWN',
}